# SPDX-License-Identifier: GPL-3.0-or-later
"""Idempotently extend ``data/actions/kicad10.json`` with curated entries.

Adds ~80 high-value KiCad-10 actions that were missing from the original
50-action seed: PCB-Setup dialogs (Stackup, Net Classes, Constraints),
Plot/Fabrication outputs (PDF, SVG, DXF, Position file), Length tuner,
Diff-Pair routing, Eeschema placement primitives (Wire/Bus/Label/Power),
Hierarchy navigation, Symbol/Footprint editor basics.

Run:
    python scripts/extend_kicad10_actions.py

Re-runs are no-ops (matches by ``id``). Schema documented in the JSON's
``_meta`` block.
"""
from __future__ import annotations

import json
import os
import sys
from typing import Any


DATA_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "kicad_mcp", "data", "actions", "kicad10.json",
)


def _a(id_: str, editor: str, shortcut: str,
       en: list[str], de: list[str],
       desc_en: str, desc_de: str,
       keywords: list[str]) -> dict[str, Any]:
    return {
        "id": id_,
        "editor": editor,
        "shortcut_default": shortcut,
        "menu_path_en": en,
        "menu_path_de": de,
        "description_en": desc_en,
        "description_de": desc_de,
        "keywords": keywords,
    }


NEW_ACTIONS: list[dict[str, Any]] = [
    # ---------- Common: File ----------
    _a("common.file.archive_project", "all", "",
       ["File", "Archive Project..."],
       ["Datei", "Projekt archivieren..."],
       "Bundle the project into a single .zip archive.",
       "Projekt in ein .zip-Archiv packen.",
       ["archive", "zip", "archivieren", "backup"]),
    _a("common.file.import_graphics", "all", "Ctrl+Shift+F",
       ["File", "Import", "Graphics..."],
       ["Datei", "Importieren", "Grafik..."],
       "Import DXF/SVG/PNG graphics into the current document.",
       "DXF/SVG/PNG-Grafiken ins aktuelle Dokument importieren.",
       ["import", "dxf", "svg", "png", "graphics", "grafik"]),

    # ---------- Common: Edit / Search ----------
    _a("common.edit.find_replace", "all", "Ctrl+Alt+F",
       ["Edit", "Find and Replace..."],
       ["Bearbeiten", "Suchen und Ersetzen..."],
       "Find text/refs and replace them.",
       "Text/Referenzen suchen und ersetzen.",
       ["find replace", "suchen ersetzen", "rename"]),
    _a("common.edit.duplicate", "all", "Ctrl+D",
       ["Edit", "Duplicate"],
       ["Bearbeiten", "Duplizieren"],
       "Duplicate the current selection.",
       "Aktuelle Auswahl duplizieren.",
       ["duplicate", "duplizieren", "copy"]),
    _a("common.edit.delete", "all", "Del",
       ["Edit", "Delete"],
       ["Bearbeiten", "Löschen"],
       "Delete the current selection.",
       "Aktuelle Auswahl löschen.",
       ["delete", "löschen", "entf"]),
    _a("common.edit.select_all", "all", "Ctrl+A",
       ["Edit", "Select All"],
       ["Bearbeiten", "Alle auswählen"],
       "Select everything in the document.",
       "Alles im Dokument auswählen.",
       ["select all", "alle auswählen"]),
    _a("common.edit.measure", "all", "Ctrl+Shift+M",
       ["Inspect", "Measure"],
       ["Inspizieren", "Messen"],
       "Activate the measurement tool.",
       "Mess-Werkzeug aktivieren.",
       ["measure", "messen", "ruler", "lineal", "distance"]),

    # ---------- Common: View ----------
    _a("common.view.zoom_redraw", "all", "F5",
       ["View", "Refresh"],
       ["Ansicht", "Aktualisieren"],
       "Redraw the canvas.",
       "Zeichenfläche neu zeichnen.",
       ["refresh", "redraw", "aktualisieren"]),
    _a("common.view.zoom_selection", "all", "Ctrl+Home",
       ["View", "Zoom to Objects"],
       ["Ansicht", "Auf Objekte einpassen"],
       "Fit the current selection to view.",
       "Aktuelle Auswahl ins Bild einpassen.",
       ["zoom selection", "zoom objects", "einpassen"]),
    _a("common.view.toggle_units", "all", "Ctrl+U",
       ["View", "Toggle Units"],
       ["Ansicht", "Einheiten umschalten"],
       "Toggle between mm/inch/mils.",
       "Zwischen mm/Zoll/mil umschalten.",
       ["units", "einheiten", "mm", "mils", "inch"]),
    _a("common.view.high_contrast", "all", "H",
       ["View", "High Contrast Mode"],
       ["Ansicht", "Hoher Kontrast"],
       "Cycle high-contrast display modes.",
       "Hochkontrast-Anzeigemodus durchschalten.",
       ["high contrast", "hochkontrast", "darken"]),

    # ---------- Common: Grid ----------
    _a("common.grid.next", "all", "N",
       ["View", "Grid", "Next Grid"],
       ["Ansicht", "Raster", "Nächstes Raster"],
       "Switch to the next grid in the list.",
       "Zum nächsten Raster der Liste wechseln.",
       ["grid", "raster", "next", "nächstes"]),
    _a("common.grid.prev", "all", "Shift+N",
       ["View", "Grid", "Previous Grid"],
       ["Ansicht", "Raster", "Vorheriges Raster"],
       "Switch to the previous grid in the list.",
       "Zum vorigen Raster der Liste wechseln.",
       ["grid", "raster", "previous", "vorheriges"]),
    _a("common.grid.fast_cycle", "all", "Alt+4",
       ["View", "Grid", "Cycle Fast Grids"],
       ["Ansicht", "Raster", "Schnellraster durchschalten"],
       "Cycle between the fast grids (Alt+1, Alt+2).",
       "Zwischen Schnellrastern (Alt+1, Alt+2) durchschalten.",
       ["fast grid", "schnellraster"]),

    # ---------- Eeschema: File / Export ----------
    _a("sch.file.export_netlist", "schematic", "",
       ["File", "Export", "Netlist..."],
       ["Datei", "Exportieren", "Netzliste..."],
       "Export the netlist (KiCad sexpr / Cadstar / OrcadPCB2 / Spice / Allegro).",
       "Netzliste exportieren (KiCad sexpr / Cadstar / OrcadPCB2 / Spice / Allegro).",
       ["netlist", "netzliste", "export", "spice"]),
    _a("sch.file.export_drawing_to_pdf", "schematic", "",
       ["File", "Plot..."],
       ["Datei", "Plotten..."],
       "Plot schematic to PDF / SVG / DXF / Postscript / HPGL.",
       "Schaltplan als PDF / SVG / DXF / Postscript / HPGL plotten.",
       ["plot", "pdf", "svg", "dxf", "schematic export"]),
    _a("sch.file.export_symbols", "schematic", "",
       ["File", "Export", "Symbols to New Library..."],
       ["Datei", "Exportieren", "Symbole in neue Bibliothek..."],
       "Export all symbols of the sheet into a library file.",
       "Alle Symbole des Schaltplans in eine Bibliothek exportieren.",
       ["export symbols", "symbole exportieren", "library"]),

    # ---------- Eeschema: Place (full set) ----------
    _a("sch.place.no_connect", "schematic", "Q",
       ["Place", "No Connection Flag"],
       ["Platzieren", "Nicht-verbunden-Flag"],
       "Place a no-connect cross on an unused pin.",
       "Nicht-verbunden-Kreuz auf ungenutzten Pin setzen.",
       ["no connect", "nc", "nicht verbunden", "ungenutzt"]),
    _a("sch.place.bus_entry", "schematic", "Z",
       ["Place", "Bus Entry"],
       ["Platzieren", "Bus-Anschluss"],
       "Place a wire-to-bus entry.",
       "Wire-zu-Bus-Anschluss platzieren.",
       ["bus entry", "bus anschluss"]),
    _a("sch.place.hierarchical_label", "schematic", "H",
       ["Place", "Hierarchical Label"],
       ["Platzieren", "Hierarchisches Label"],
       "Place a hierarchical label (sub-sheet I/O).",
       "Hierarchisches Label platzieren (Sub-Sheet-I/O).",
       ["hierarchical label", "hierarchisches label", "sub sheet"]),
    _a("sch.place.text", "schematic", "T",
       ["Place", "Text"],
       ["Platzieren", "Text"],
       "Place a free-text annotation.",
       "Freie Textnotiz platzieren.",
       ["text", "annotation", "notiz"]),
    _a("sch.place.image", "schematic", "",
       ["Place", "Image"],
       ["Platzieren", "Bild"],
       "Place an image on the schematic.",
       "Bild auf dem Schaltplan platzieren.",
       ["image", "bild", "logo"]),

    # ---------- Eeschema: Navigate ----------
    _a("sch.nav.show_hierarchy", "schematic", "Ctrl+H",
       ["View", "Show Hierarchy Navigator"],
       ["Ansicht", "Hierarchie-Navigator anzeigen"],
       "Open the hierarchical sheet navigator panel.",
       "Hierarchie-Navigator-Panel öffnen.",
       ["hierarchy", "navigator", "hierarchie"]),
    _a("sch.nav.next_sheet", "schematic", "PgDn",
       ["View", "Next Sheet"],
       ["Ansicht", "Nächstes Blatt"],
       "Jump to the next sub-sheet.",
       "Zum nächsten Sub-Blatt springen.",
       ["next sheet", "nächstes blatt", "pgdn"]),
    _a("sch.nav.prev_sheet", "schematic", "PgUp",
       ["View", "Previous Sheet"],
       ["Ansicht", "Vorheriges Blatt"],
       "Jump to the previous sub-sheet.",
       "Zum vorigen Sub-Blatt springen.",
       ["previous sheet", "vorheriges blatt", "pgup"]),
    _a("sch.nav.leave_sheet", "schematic", "Alt+Back",
       ["View", "Leave Sheet"],
       ["Ansicht", "Blatt verlassen"],
       "Go up one level in the sheet hierarchy.",
       "Eine Ebene in der Blatt-Hierarchie nach oben.",
       ["leave sheet", "blatt verlassen", "up hierarchy"]),
    _a("sch.nav.up_hierarchy", "schematic", "Alt+Up",
       ["View", "Up in Hierarchy"],
       ["Ansicht", "Hierarchie hoch"],
       "Move one level up in the hierarchy.",
       "Eine Ebene in der Hierarchie nach oben gehen.",
       ["up hierarchy", "hierarchie hoch"]),

    # ---------- Eeschema: Edit ----------
    _a("sch.edit.properties", "schematic", "E",
       ["Edit", "Properties"],
       ["Bearbeiten", "Eigenschaften"],
       "Open properties dialog of the selected item.",
       "Eigenschafts-Dialog des ausgewählten Items öffnen.",
       ["properties", "eigenschaften", "edit"]),
    _a("sch.edit.move", "schematic", "M",
       ["Edit", "Move"],
       ["Bearbeiten", "Verschieben"],
       "Move the selected item (no wire-drag).",
       "Ausgewähltes Item verschieben (ohne Wire-Drag).",
       ["move", "verschieben"]),
    _a("sch.edit.drag", "schematic", "G",
       ["Edit", "Drag"],
       ["Bearbeiten", "Ziehen"],
       "Drag the selected item (with wire-keep).",
       "Ausgewähltes Item ziehen (Wires bleiben verbunden).",
       ["drag", "ziehen", "wire keep"]),
    _a("sch.edit.rotate_ccw", "schematic", "R",
       ["Edit", "Rotate CCW"],
       ["Bearbeiten", "Drehen CCW"],
       "Rotate counter-clockwise (R).",
       "Gegen Uhrzeigersinn drehen (R).",
       ["rotate", "drehen", "ccw"]),
    _a("sch.edit.rotate_cw", "schematic", "Shift+R",
       ["Edit", "Rotate CW"],
       ["Bearbeiten", "Drehen CW"],
       "Rotate clockwise (Shift+R).",
       "Im Uhrzeigersinn drehen (Shift+R).",
       ["rotate cw", "drehen cw"]),
    _a("sch.edit.mirror_x", "schematic", "X",
       ["Edit", "Mirror Horizontally"],
       ["Bearbeiten", "Horizontal spiegeln"],
       "Mirror horizontally (X).",
       "Horizontal spiegeln (X).",
       ["mirror x", "spiegeln horizontal"]),
    _a("sch.edit.mirror_y", "schematic", "Y",
       ["Edit", "Mirror Vertically"],
       ["Bearbeiten", "Vertikal spiegeln"],
       "Mirror vertically (Y).",
       "Vertikal spiegeln (Y).",
       ["mirror y", "spiegeln vertikal"]),
    _a("sch.edit.edit_value", "schematic", "V",
       ["Edit", "Edit Value"],
       ["Bearbeiten", "Wert ändern"],
       "Edit the Value field of the selected symbol.",
       "Wert-Feld des ausgewählten Symbols editieren.",
       ["edit value", "wert", "value"]),
    _a("sch.edit.edit_reference", "schematic", "U",
       ["Edit", "Edit Reference"],
       ["Bearbeiten", "Referenz ändern"],
       "Edit the Reference field (e.g. R5 → R10).",
       "Referenz-Feld editieren (z.B. R5 → R10).",
       ["edit reference", "referenz", "ref"]),
    _a("sch.edit.edit_footprint", "schematic", "F",
       ["Edit", "Edit Footprint"],
       ["Bearbeiten", "Footprint ändern"],
       "Assign / change the footprint of the symbol.",
       "Footprint des Symbols zuweisen / ändern.",
       ["edit footprint", "footprint zuweisen"]),
    _a("sch.edit.swap", "schematic", "Alt+S",
       ["Edit", "Swap"],
       ["Bearbeiten", "Tauschen"],
       "Swap position of two selected items.",
       "Position zweier ausgewählter Items tauschen.",
       ["swap", "tauschen"]),
    _a("sch.edit.autoplace_fields", "schematic", "O",
       ["Edit", "Autoplace Fields"],
       ["Bearbeiten", "Felder auto-platzieren"],
       "Automatically place symbol fields (Reference, Value).",
       "Symbol-Felder (Referenz, Wert) automatisch platzieren.",
       ["autoplace fields", "felder automatisch"]),

    # ---------- Eeschema: Tools ----------
    _a("sch.tools.symbol_to_lib", "schematic", "Ctrl+Shift+E",
       ["Tools", "Edit Library Symbol with Symbol Editor"],
       ["Werkzeuge", "Bibliotheks-Symbol mit Symbol-Editor öffnen"],
       "Open the library symbol of the selected instance in Symbol Editor.",
       "Bibliotheks-Symbol des ausgewählten Symbols im Symbol-Editor öffnen.",
       ["library symbol", "lib symbol", "symbol editor"]),
    _a("sch.tools.symbol_fields_editor", "schematic", "",
       ["Tools", "Edit Symbol Fields..."],
       ["Werkzeuge", "Symbol-Felder bearbeiten..."],
       "Open the spreadsheet-style symbol fields editor.",
       "Symbol-Felder-Editor (Tabellenansicht) öffnen.",
       ["symbol fields", "felder editor", "spreadsheet"]),
    _a("sch.tools.update_sch_from_pcb", "schematic", "",
       ["Tools", "Update Schematic from PCB..."],
       ["Werkzeuge", "Schaltplan aus PCB aktualisieren..."],
       "Sync schematic with changes made in the PCB editor.",
       "Schaltplan mit Änderungen aus dem PCB-Editor synchronisieren.",
       ["update schematic from pcb", "back-annotation"]),
    _a("sch.tools.assign_footprints", "schematic", "",
       ["Tools", "Assign Footprints..."],
       ["Werkzeuge", "Footprints zuweisen..."],
       "Open the footprint-assignment dialog (CvPcb).",
       "Footprint-Zuweisungs-Dialog (CvPcb) öffnen.",
       ["assign footprints", "footprints zuweisen", "cvpcb"]),

    # ---------- Eeschema: Setup ----------
    _a("sch.setup.schematic_setup", "schematic", "",
       ["File", "Schematic Setup..."],
       ["Datei", "Schaltplan-Einstellungen..."],
       "Open the schematic setup dialog (formatting, field templates, ERC).",
       "Schaltplan-Setup öffnen (Formatierung, Feldvorlagen, ERC).",
       ["schematic setup", "schaltplan setup", "formatting"]),

    # ---------- PCB: Place ----------
    _a("pcb.place.footprint", "pcb", "A",
       ["Place", "Add Footprint"],
       ["Platzieren", "Footprint hinzufügen"],
       "Place a footprint from a library.",
       "Footprint aus Bibliothek platzieren.",
       ["place footprint", "footprint hinzufügen", "add fp"]),
    _a("pcb.place.text", "pcb", "Ctrl+Shift+T",
       ["Place", "Text"],
       ["Platzieren", "Text"],
       "Place a text on the PCB.",
       "Text auf der Platine platzieren.",
       ["place text", "text platzieren"]),
    _a("pcb.place.zone", "pcb", "Ctrl+Shift+Z",
       ["Place", "Zone"],
       ["Platzieren", "Zone"],
       "Place a Cu pour zone.",
       "Kupferfläche / Zone platzieren.",
       ["place zone", "kupferfläche", "pour"]),
    _a("pcb.place.zone_cutout", "pcb", "Shift+C",
       ["Place", "Zone Cutout"],
       ["Platzieren", "Zonen-Ausschnitt"],
       "Cut a hole into an existing zone.",
       "Loch in bestehende Zone schneiden.",
       ["zone cutout", "zonen ausschnitt"]),
    _a("pcb.place.rule_area", "pcb", "Ctrl+Shift+K",
       ["Place", "Rule Area"],
       ["Platzieren", "Regel-Bereich"],
       "Place a keepout / rule area.",
       "Keepout / Regel-Bereich platzieren.",
       ["rule area", "keepout", "regel bereich"]),
    _a("pcb.place.dimension_orthogonal", "pcb", "Ctrl+Shift+H",
       ["Place", "Dimension", "Orthogonal"],
       ["Platzieren", "Bemaßung", "Orthogonal"],
       "Place an orthogonal dimension line.",
       "Orthogonale Bemaßungslinie platzieren.",
       ["dimension", "bemaßung", "orthogonal"]),
    _a("pcb.place.arc", "pcb", "Ctrl+Shift+A",
       ["Place", "Arc"],
       ["Platzieren", "Bogen"],
       "Draw an arc segment.",
       "Bogensegment zeichnen.",
       ["arc", "bogen", "circle segment"]),
    _a("pcb.place.line", "pcb", "Ctrl+Shift+L",
       ["Place", "Line"],
       ["Platzieren", "Linie"],
       "Draw a graphic line.",
       "Grafische Linie zeichnen.",
       ["line", "linie", "graphic"]),
    _a("pcb.place.circle", "pcb", "Ctrl+Shift+C",
       ["Place", "Circle"],
       ["Platzieren", "Kreis"],
       "Draw a graphic circle.",
       "Grafischen Kreis zeichnen.",
       ["circle", "kreis"]),

    # ---------- PCB: Route ----------
    _a("pcb.route.diff_pair", "pcb", "6",
       ["Route", "Differential Pair"],
       ["Routen", "Differential-Paar"],
       "Route a differential pair.",
       "Differential-Paar routen.",
       ["diff pair", "differential", "differential paar"]),
    _a("pcb.route.length_tuner_single", "pcb", "7",
       ["Route", "Tune Track Length"],
       ["Routen", "Track-Länge abstimmen"],
       "Tune length of a single track.",
       "Länge einer einzelnen Leiterbahn abstimmen.",
       ["length tuner", "length tune", "längenabstimmung"]),
    _a("pcb.route.length_tuner_diff", "pcb", "8",
       ["Route", "Tune Differential Pair Length"],
       ["Routen", "Differential-Paar-Länge abstimmen"],
       "Tune length of a differential pair.",
       "Länge eines Differential-Paars abstimmen.",
       ["length tuner diff", "diff pair length"]),
    _a("pcb.route.length_tuner_skew", "pcb", "9",
       ["Route", "Tune Differential Pair Skew"],
       ["Routen", "Differential-Paar-Versatz abstimmen"],
       "Tune skew of a differential pair.",
       "Versatz eines Differential-Paars abstimmen.",
       ["skew tuner", "differential skew", "versatz"]),
    _a("pcb.route.track_width_inc", "pcb", "W",
       ["Route", "Increase Track Width"],
       ["Routen", "Leiterbahnbreite erhöhen"],
       "Switch to the next-larger track width.",
       "Zur nächstgrößeren Leiterbahnbreite wechseln.",
       ["track width", "breite", "width"]),
    _a("pcb.route.track_width_dec", "pcb", "Shift+W",
       ["Route", "Decrease Track Width"],
       ["Routen", "Leiterbahnbreite verringern"],
       "Switch to the next-smaller track width.",
       "Zur nächstkleineren Leiterbahnbreite wechseln.",
       ["track width", "breite", "width", "decrease"]),
    _a("pcb.route.via_size_inc", "pcb", "'",
       ["Route", "Increase Via Size"],
       ["Routen", "Via-Größe erhöhen"],
       "Switch to the next-larger via size.",
       "Zur nächstgrößeren Via-Größe wechseln.",
       ["via size", "via größe"]),
    _a("pcb.route.posture", "pcb", "/",
       ["Route", "Switch Posture"],
       ["Routen", "Posture wechseln"],
       "Toggle 45° corner direction while routing.",
       "45°-Winkel-Richtung während des Routings umschalten.",
       ["posture", "switch posture", "45 degree"]),
    _a("pcb.route.drag_45", "pcb", "D",
       ["Edit", "Drag (45° preserve)"],
       ["Bearbeiten", "Ziehen (45° beibehalten)"],
       "Drag tracks while preserving 45° angles.",
       "Tracks ziehen, 45°-Winkel beibehalten.",
       ["drag 45", "ziehen 45"]),
    _a("pcb.route.drag_free", "pcb", "G",
       ["Edit", "Drag (free angle)"],
       ["Bearbeiten", "Ziehen (frei)"],
       "Drag tracks with free-angle routing.",
       "Tracks mit freier Winkel-Routing ziehen.",
       ["drag free", "ziehen frei"]),

    # ---------- PCB: Setup Dialogs ----------
    _a("pcb.setup.board_setup", "pcb", "",
       ["File", "Board Setup..."],
       ["Datei", "Board-Setup..."],
       "Open the master board setup dialog (Stackup, Net Classes, Constraints).",
       "Board-Setup-Hauptdialog öffnen (Lagenaufbau, Netzklassen, Designregeln).",
       ["board setup", "platinen setup", "stackup", "net classes", "constraints"]),
    _a("pcb.setup.net_classes", "pcb", "",
       ["File", "Board Setup...", "Net Classes"],
       ["Datei", "Board-Setup...", "Netzklassen"],
       "Configure net-class assignments (track widths, clearances).",
       "Netzklassen-Zuweisungen konfigurieren (Leiterbahnbreite, Abstände).",
       ["net classes", "netzklassen", "rules", "regelsatz"]),
    _a("pcb.setup.constraints", "pcb", "",
       ["File", "Board Setup...", "Design Rules", "Constraints"],
       ["Datei", "Board-Setup...", "Designregeln", "Designvorgaben"],
       "Configure DRC constraints (min track, min hole, copper-to-edge).",
       "DRC-Designvorgaben konfigurieren (min. Leiterbahn, min. Bohrung, Cu-zu-Rand).",
       ["constraints", "design rules", "designregeln", "drc"]),
    _a("pcb.setup.stackup", "pcb", "",
       ["File", "Board Setup...", "Board Stackup", "Physical Stackup"],
       ["Datei", "Board-Setup...", "Lagenaufbau", "Physikalischer Lagenaufbau"],
       "Configure the PCB layer stackup (dielectric thicknesses, copper weights).",
       "PCB-Lagenaufbau konfigurieren (Dielektrikum-Dicken, Cu-Gewichte).",
       ["stackup", "lagenaufbau", "layer thickness"]),
    _a("pcb.setup.layers", "pcb", "",
       ["File", "Board Setup...", "Board Editor Layers"],
       ["Datei", "Board-Setup...", "Board-Editor-Layer"],
       "Configure enabled layers + their names/colors.",
       "Aktivierte Layer + Namen/Farben konfigurieren.",
       ["layer setup", "layer namen", "board layers"]),
    _a("pcb.setup.solder_mask", "pcb", "",
       ["File", "Board Setup...", "Solder Mask/Paste"],
       ["Datei", "Board-Setup...", "Lötstopplack/Lötpaste"],
       "Configure solder-mask and paste-mask expansion defaults.",
       "Lötstopplack- und Lötpasten-Expansion-Defaults konfigurieren.",
       ["solder mask", "lötstopplack", "paste mask", "lötpaste"]),
    _a("pcb.setup.text_drawing", "pcb", "",
       ["File", "Board Setup...", "Text & Graphics", "Defaults"],
       ["Datei", "Board-Setup...", "Text & Grafik", "Standardwerte"],
       "Configure default text size, line thickness, dimension format.",
       "Standard-Textgröße, Linienstärke, Bemaßungsformat konfigurieren.",
       ["text defaults", "text standard", "drawing defaults"]),

    # ---------- PCB: Tools ----------
    _a("pcb.tools.update_sch_from_pcb", "pcb", "",
       ["Tools", "Update Schematic from PCB..."],
       ["Werkzeuge", "Schaltplan aus PCB aktualisieren..."],
       "Back-sync changes from PCB to schematic.",
       "Änderungen vom PCB zurück in den Schaltplan synchronisieren.",
       ["update schematic from pcb", "back-annotation", "rückannotation"]),
    _a("pcb.tools.cleanup_tracks_vias", "pcb", "",
       ["Tools", "Cleanup Tracks & Vias..."],
       ["Werkzeuge", "Leiterbahnen & Vias aufräumen..."],
       "Remove redundant/overlapping tracks and unconnected vias.",
       "Redundante/überlappende Leiterbahnen und nicht-verbundene Vias entfernen.",
       ["cleanup tracks", "tracks aufräumen", "redundant"]),
    _a("pcb.tools.global_deletions", "pcb", "",
       ["Edit", "Global Deletions..."],
       ["Bearbeiten", "Globales Löschen..."],
       "Delete tracks/vias/zones globally by filter.",
       "Tracks/Vias/Zonen global per Filter löschen.",
       ["global deletions", "globales löschen", "delete all"]),
    _a("pcb.tools.position_file", "pcb", "",
       ["File", "Fabrication Outputs", "Component Placement (.pos, .gbr)..."],
       ["Datei", "Fertigungs-Ausgaben", "Bauteil-Position (.pos, .gbr)..."],
       "Export component position file for pick-and-place.",
       "Bauteil-Positions-Datei für Pick-and-Place exportieren.",
       ["position file", "pos file", "pick place", "bauteil position"]),
    _a("pcb.tools.fab_outputs", "pcb", "",
       ["File", "Fabrication Outputs"],
       ["Datei", "Fertigungs-Ausgaben"],
       "Submenu with all fabrication output exports.",
       "Untermenü mit allen Fertigungs-Ausgabe-Exports.",
       ["fab outputs", "fertigung", "manufacturing"]),
    _a("pcb.tools.swap_layers", "pcb", "",
       ["Edit", "Swap Layers..."],
       ["Bearbeiten", "Layer tauschen..."],
       "Swap items between two copper layers.",
       "Items zwischen zwei Cu-Layern tauschen.",
       ["swap layers", "layer tauschen"]),

    # ---------- PCB: Inspect ----------
    _a("pcb.inspect.net_inspector", "pcb", "",
       ["Inspect", "Net Inspector"],
       ["Inspizieren", "Netz-Inspektor"],
       "Show the net inspector (length, vias, layers per net).",
       "Netz-Inspektor zeigen (Länge, Vias, Layer pro Netz).",
       ["net inspector", "netz inspektor", "trace length"]),
    _a("pcb.inspect.show_net_navigator", "pcb", "",
       ["View", "Show Net Navigator"],
       ["Ansicht", "Netz-Navigator anzeigen"],
       "Open the net navigator panel.",
       "Netz-Navigator-Panel öffnen.",
       ["net navigator", "netz navigator"]),
    _a("pcb.inspect.highlight_net", "pcb", "`",
       ["Inspect", "Highlight Net"],
       ["Inspizieren", "Netz hervorheben"],
       "Highlight the selected net in colour.",
       "Ausgewähltes Netz farblich hervorheben.",
       ["highlight net", "netz hervorheben"]),
    _a("pcb.inspect.clear_highlight", "pcb", "~",
       ["Inspect", "Clear Net Highlight"],
       ["Inspizieren", "Netz-Hervorhebung löschen"],
       "Clear all net highlights.",
       "Alle Netz-Hervorhebungen entfernen.",
       ["clear highlight", "hervorhebung löschen"]),

    # ---------- PCB: View ----------
    _a("pcb.view.layer_toggle", "pcb", "V",
       ["View", "Switch Layer / Add Via"],
       ["Ansicht", "Layer wechseln / Via hinzufügen"],
       "Switch active layer (places via if routing).",
       "Aktive Layer wechseln (setzt Via beim Routen).",
       ["layer toggle", "switch layer", "via", "layer wechseln"]),
    _a("pcb.view.layer_alpha_inc", "pcb", "}",
       ["View", "Increase Layer Opacity"],
       ["Ansicht", "Layer-Deckkraft erhöhen"],
       "Increase opacity of the active layer.",
       "Deckkraft der aktiven Layer erhöhen.",
       ["layer alpha", "deckkraft", "opacity"]),
    _a("pcb.view.layer_alpha_dec", "pcb", "{",
       ["View", "Decrease Layer Opacity"],
       ["Ansicht", "Layer-Deckkraft verringern"],
       "Decrease opacity of the active layer.",
       "Deckkraft der aktiven Layer verringern.",
       ["layer alpha", "deckkraft", "opacity"]),

    # ---------- PCB: File / Export ----------
    _a("pcb.file.plot_pdf", "pcb", "",
       ["File", "Plot...", "Output Format: PDF"],
       ["Datei", "Plotten...", "Ausgabeformat: PDF"],
       "Plot the PCB to PDF.",
       "PCB als PDF plotten.",
       ["plot pdf", "pdf export", "pdf"]),
    _a("pcb.file.plot_svg", "pcb", "",
       ["File", "Export", "SVG..."],
       ["Datei", "Exportieren", "SVG..."],
       "Plot the PCB to SVG.",
       "PCB als SVG plotten.",
       ["plot svg", "svg export"]),
    _a("pcb.file.plot_dxf", "pcb", "",
       ["File", "Plot...", "Output Format: DXF"],
       ["Datei", "Plotten...", "Ausgabeformat: DXF"],
       "Plot the PCB to DXF.",
       "PCB als DXF plotten.",
       ["plot dxf", "dxf export"]),
    _a("pcb.file.archive_3d_models", "pcb", "",
       ["File", "Archive 3D Models"],
       ["Datei", "3D-Modelle archivieren"],
       "Embed 3D models into the PCB file (portability).",
       "3D-Modelle ins PCB-File einbetten (Portabilität).",
       ["archive 3d", "3d modelle archivieren", "embed"]),

    # ---------- KiCad Project Manager ----------
    _a("kicad.proj.edit_symbol_library", "all", "Ctrl+L",
       ["Tools", "Edit Symbol Library"],
       ["Werkzeuge", "Symbol-Bibliothek bearbeiten"],
       "Open the symbol library editor.",
       "Symbol-Bibliotheks-Editor öffnen.",
       ["symbol library", "symbol bibliothek", "editor"]),
    _a("kicad.proj.edit_footprints", "all", "Ctrl+F",
       ["Tools", "Edit Footprints"],
       ["Werkzeuge", "Footprints bearbeiten"],
       "Open the footprint editor.",
       "Footprint-Editor öffnen.",
       ["footprint editor", "footprint bearbeiten"]),
    _a("kicad.proj.view_gerbers", "all", "Ctrl+G",
       ["Tools", "Open Gerber Viewer"],
       ["Werkzeuge", "Gerber-Viewer öffnen"],
       "Open the Gerber Viewer (GerbView).",
       "Gerber-Viewer (GerbView) öffnen.",
       ["gerber viewer", "gerbview"]),
    _a("kicad.proj.pcb_calculator", "all", "",
       ["Tools", "PCB Calculator"],
       ["Werkzeuge", "PCB-Rechner"],
       "Open the PCB calculator (trace width, electric, R-divider).",
       "PCB-Rechner öffnen (Leiterbahnbreite, Elektrik, R-Teiler).",
       ["pcb calculator", "rechner", "trace width", "wizards"]),
    _a("kicad.proj.plugin_manager", "all", "Ctrl+M",
       ["Tools", "Plugin and Content Manager"],
       ["Werkzeuge", "Plugin- und Inhaltsverwaltung"],
       "Manage installed plugins and content packs.",
       "Plugin- und Content-Verwaltung öffnen.",
       ["plugin manager", "content manager", "plugin", "pcm"]),

    # ---------- 3D Viewer ----------
    _a("pcb.view3d.flip_view", "pcb", "F",
       ["3D Viewer", "View", "Flip Board"],
       ["3D-Betrachter", "Ansicht", "Platine wenden"],
       "Flip the PCB top/bottom in the 3D view.",
       "PCB in der 3D-Ansicht wenden (Top/Bottom).",
       ["flip board", "3d flip", "platine wenden"]),
    _a("pcb.view3d.attribute_smd", "pcb", "S",
       ["3D Viewer", "View", "Show SMD"],
       ["3D-Betrachter", "Ansicht", "SMD anzeigen"],
       "Toggle SMD components in 3D viewer.",
       "SMD-Bauteile im 3D-Betrachter ein/aus.",
       ["smd 3d", "smd anzeigen"]),
    _a("pcb.view3d.attribute_tht", "pcb", "T",
       ["3D Viewer", "View", "Show THT"],
       ["3D-Betrachter", "Ansicht", "THT anzeigen"],
       "Toggle THT components in 3D viewer.",
       "THT-Bauteile im 3D-Betrachter ein/aus.",
       ["tht 3d", "tht anzeigen", "through hole"]),
]


def main() -> int:
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)

    existing = {a["id"]: a for a in data["actions"]}
    added = 0
    skipped = 0
    for na in NEW_ACTIONS:
        if na["id"] in existing:
            skipped += 1
            continue
        data["actions"].append(na)
        added += 1

    # Bump _meta.version, document the extension
    meta = data.setdefault("_meta", {})
    meta["version"] = "1.1"
    meta["total_actions"] = len(data["actions"])

    # Pretty-write with 2-space indent (matches original style).
    with open(DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Added {added} actions, skipped {skipped} duplicates. "
          f"Total now: {len(data['actions'])} (was 50).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
